project_name: stargazer

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/stargazer/main.go
    binary: stargazer

archives:
  - format: tar.gz
    # use zip for windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "docker.io/maplecitymadman/stargazer:{{ .Version }}"
      - "docker.io/maplecitymadman/stargazer:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx

  - image_templates:
      - "docker.io/maplecitymadman/stargazer:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64
    use: buildx

docker_manifests:
  - name_template: "docker.io/maplecitymadman/stargazer:{{ .Version }}"
    image_templates:
      - "docker.io/maplecitymadman/stargazer:{{ .Version }}"
      - "docker.io/maplecitymadman/stargazer:{{ .Version }}-arm64"
  - name_template: "docker.io/maplecitymadman/stargazer:latest"
    image_templates:
      - "docker.io/maplecitymadman/stargazer:latest"
      - "docker.io/maplecitymadman/stargazer:{{ .Version }}-arm64"

release:
  extra_files:
    - glob: ./desktop-artifacts/*
