apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stargazer-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard